sudo: required
dist: trusty
language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - ubuntu-toolchain-r-test
    packages:
      - clang-5.0
      - g++-7
      - cppcheck

os:
  - linux
  - osx

env:
  - COMPILER=clang CONFIG=Debug
  - COMPILER=clang CONFIG=Release
  - COMPILER=gcc CONFIG=Debug
  - COMPILER=gcc CONFIG=Release

matrix:
  exclude:
    - os: osx
      env: COMPILER=gcc CONFIG=Debug
    - os: osx
      env: COMPILER=clang CONFIG=Debug
    - os: osx
      env: COMPILER=clang CONFIG=Release

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install gcc; fi
  - if [[ "$COMPILER" == "clang" ]]; then CC=clang-5.0 && CXX=clang++-5.0; fi
  - if [[ "$COMPILER" == "gcc" ]]; then CC=gcc-7 && CXX=g++-7; fi
  - echo $CC
  - echo $CXX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cppcheck; fi
  - sudo pip install cpplint
  - ./scripts/install-glog.sh

script:
  # build
  - cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=$CONFIG
  - cmake --build build --config $CONFIG
  # lint
  - cppcheck --error-exitcode=1 src
  - cpplint --recursive src

